---
apiVersion: v1
kind: Secret
metadata:
  name: devhub-val-ordersval-gitops-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/devhub-backendvvvs-gitops