---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devhub-val-ordersval-gitops-dev-build
  namespace: devhub
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: devhub_orders
  source:
    repoURL: https://github.com/devhub-mad/devhub-backendvvvs-gitops
    targetRevision: HEAD
    path: ./helm/build
  destination:
    server: https://kubernetes.default.svc
    namespace: devhub-val-ordersval-gitops-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy      
